#!/bin/sh /etc/rc.common
# Middle-LED status daemon for the GL.iNet GL-MT300N-V2.

START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/glstatusd
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	/usr/bin/glstate off
}
